# Generated by Django 4.1.3 on 2022-11-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
